[project]
name = "myapp-pkg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Masaki Kobayashi", email = "bayashi.cl@gmail.com" } 
]
requires-python = ">=3.12"
dependencies = [
    "myapp-utils",
    "pendulum>=2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
myapp-utils = { workspace = true }
