[project]
name = "myapp-invalid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Masaki Kobayashi", email = "bayashi.cl@gmail.com" } 
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
